#!/usr/bin/bash
setxkbmap us,cz -variant ,ucw -option grp:caps_switch
#feh --bg-max ~/bg0.png
kitty&
nm-applet&
copyq&
kmix&
telegram-desktop&

if test "$(cat /etc/hostname)" = "flower"
then
	#~/.screenlayout/default.sh
	#picom --experimental-backends --backend glx --blur-method dual_kawase --blur-strength 4 # doesnt work lol
	copyq&
	firefox&
	discord&
	#steam&
fi
