#!/usr/bin/bash
setxkbmap us,cz -variant ,ucw -option grp:caps_switch
#feh --bg-max ~/bg0.png
kitty&
#nm-applet&
copyq&
kmix&
telegram-desktop&

if test "$(cat /etc/hostname)" = "flower"
then
	~/.screenlayout/default.sh
	picom -b -D 1 &
	feh --bg-fill ~/Documents/bg-sm.png ~/Documents/bg.png
	#firefox&
	#discord&
	#steam&
fi
