#!/bin/bash
pt=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage)
ft=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep capacity)
f=${ft:25:2}
p=${pt:24:3}
echo $p"/"$f
