#!/bin/bash
usage=$(free -m | grep Swap | awk '{usage=($3/1000)} END {print usage}')
full=$(free -m | grep Swap | awk '{full=($2/1000)} END {print full}')
usage=${usage:0:1}
full=${full:0:1}
echo $usage"/"$full
